### ISSUE TITLE
[bug] Autofocus button mapping input box

### ISSUE THREAD

**Issue by RuudBurger** [unfoldedcircle/feature-and-bug-tracker#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Adding new things would be made a lot easier if some of the modals/popup boxes have their input autofocused when you open them.

### How to Reproduce

Go to a remote, map a button to an IR command, no autofocus.

### Expected behavior

Button mapping popup should autofocus on the search input.

<img width="474" alt="Screenshot 2023-09-04 at 20 39 14" src="https://github.com/unfoldedcircle/bug-reports/assets/38136/81659bc3-d524-4b5e-84fd-71788db6b5cf">

### What part of the system affected by the problem?

Web Configurator

**Comment by martonborzak** [comment]
This has been fixed in a previous update.
