### ISSUE TITLE
[bug] Set brightness still not working in macros

### ISSUE THREAD

**Issue by Laess3r** [unfoldedcircle/feature-and-bug-tracker#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi!
Thank you for fixing https://github.com/unfoldedcircle/bug-reports/issues/8.

The values are stored now, but unfortunately the "Set brightness" feature is **not** working when trying to use these macros!

I tested with both Philips Hue and Home Assistant devices - and received different errors.

### How to Reproduce

1. Set up a macro that uses "set brightness"
2. Use it on the remote
3. When using a Hue device the remote will show "**TimedOut**" after some seconds
4. WHen using a Home Assistant device it will show "**BadRequest: Invalid cmd_id brightness."**

### Expected behavior

I expect the "Set brightness" feature to work with the integrations

### System version

v.1.1.1

### What part of the system affected by the problem?

Core

**Comment by zehnm** [comment]
Unfortunately the fix #8 was incomplete: the web-configurator sets the wrong `cmd_id` for brightness :-(
This happens for macros and activities.

We'll fix that, and probably also add more validations to the Core API, so the web-configurator cannot set an invalid command identifier in the first place.

**Comment by zehnm** [comment]
After further analysis we will keep the web-configurator as is and create a fix in the core to use the correct commands.
- Non working commands: light brightness, light colour temperature, light colour, climate target temperature
- Affects: macros, activity sequences, activity button & UI element commands
- Changing it to the "intended way" would make the related entities invalid, or require a non-trivial data cleanup

I will also check and enhance the API documentation for the command handling.

**Comment by zehnm** [comment]
This has _almost_ been fixed in 1.2.0:
- setting brightness value (and other commands with parameters) in the web-configurator works
- running the macro or activity don't throw errors anymore

However, the brightness scaling from % to brightness value "got lost". E.g. setting brightness to 50% will result to 20% 😏

Estimated fix: next week!

**Comment by zehnm** [comment]
Fixed in 1.3.1
