### ISSUE TITLE
[bug] webconfigurator settings page - Error on config load

### ISSUE THREAD

**Issue by Armadill0** [unfoldedcircle/feature-and-bug-tracker#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Going to the Remotes settings page in the web configurator you can see an error above and a little behind the Display&Brightness section:
![image](https://github.com/unfoldedcircle/bug-reports/assets/6536990/54361695-9a52-4303-983e-cb27d5b425ba)

Error message: `Error on config load CanceledError: canceled`

### How to Reproduce

1. Go to web configurator and login
2. Click on burger menu icon
3. Select "Settings"
4. Look above Display & Birghtness section as sown above in the screenshot.

### Expected behavior

No error being shown.

### System version

v1.1.1

### What part of the system affected by the problem?

Web Configurator

**Comment by Armadill0** [comment]
I have the feeling this happens only when the webconfigurator browser session expired. Unfortunately this seems to be a general issue with the expired session with my Vivaldi browser, that the interface doesn't detect the expired session and still tries to do things.

**Comment by martonborzak** [comment]
This has been fixed in a previous update.
