### ISSUE TITLE
Macros cannot be assigned other symbols

### ISSUE THREAD

**Issue by SidM01** [unfoldedcircle/feature-and-bug-tracker#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Macros cannot be assigned other symbols, 

### How to Reproduce

1. Go to Activities & Macros
2. Go on one Macro and klick edit
3. The name can be changed, but when you click on the symbol, no symbol selection window is displayed
4. The standard symbol is also not displayed in the editing window

### Expected behavior

Change the macro Symbol

### System version

v1.1.1

**Comment by zehnm** [comment]
We will improve the icon selection for entities not having an icon already.

At the moment the icon selection only works when you manage the click / press on the thin line below the `Icon` label:

![image](https://github.com/unfoldedcircle/bug-reports/assets/17356629/ba5bd643-58ea-40a5-b429-fb184bd733a9)

**Comment by zehnm** [comment]
Fixed in 1.3.2
