### ISSUE TITLE
Symbols are not displayed correctly when changed

### ISSUE THREAD

**Issue by SidM01** [unfoldedcircle/feature-and-bug-tracker#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Under User Interface/User, the entity icons are not displayed in the editor after changing. You first have to go back and then return to the user, then the previously changed symbol will be displayed. The change can be seen immediately on the remote.

### How to Reproduce

1. Go to User Interface/User
2. Change a Icon of an Entity
3. The icon remains the same.
4. Go back and then go back to the user
5. The icon has changed

### Expected behavior

The icon should change immediately.

### System version

v1.1.1

### What part of the system affected by the problem?

UI, Web Configurator

**Comment by zehnm** [comment]
Added to our backlog, we'll update this issue when we have a fix.

**Comment by zehnm** [comment]
No longer reproducable with current firmware, changed entity icons appear immediatly on the page
