### ISSUE TITLE
Activity details page on remote shows IR Set name instead of entity name

### ISSUE THREAD

**Issue by Talkabout** [unfoldedcircle/feature-and-bug-tracker#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the activity details page it shows the IR set name instead of the name I have chosen for the entity.

### How to Reproduce

1. Create "IR remote" and name it "test"
2. select "Generic AVR 1" IR set
3. Create activity containing this entity
4. Enable activity on remote
5. Go to activity details page by tapping on the top bar
6. In the list of entities you will see "Generic AVR 1" instead of "test"

### Expected behavior

The activity details page should show the entity name chosen in the web configurator, not the IR set name.

### System version

1.1.1

### What part of the system affected by the problem?

UI

**Comment by martonborzak** [comment]
I was not able to reproduce on `1.4.3`. If the issue is still there, please reopen the issue.

**Comment by leoschweizer** [comment]
@martonborzak I noticed the same issue on 1.4.3 but with the "builtin" IR remote configurations. It still shows labels like "Generic AVR 1" on that screen instead of my custom entity names.

**Comment by Talkabout** [comment]
@martonborzak same for me. Still showing "Generic AVR 1" in the activity details.

**Comment by martonborzak** [comment]
I have just tried again following the same steps, but cannot reproduce it.

I create a new remote (built-in or blank), give it a name, then create an activity and add this remote to it. In the `Tap for more` menu I see the given name.

**Comment by Talkabout** [comment]
Hi @martonborzak,

I can tell you my use case:

- create a remote, name it "test"
- inside this remote select ir dataset "Generic AVR 1"
- add this remote to an activity

On the remote:

- start the new activity
- go to activity details
- I see "Generic AVR 1" for that entity, not "test" as I would expect

Hope that makes it clear.

**Comment by martonborzak** [comment]
@Talkabout I'm doing exactly the same thing and cannot reproduce.

However found another issue, that I have fixed now: Renaming remotes were not reflected in the activity list.

**Comment by Talkabout** [comment]
Ok, I can confirm that it works for new ir remotes but not for existing ones. Maybe this gets fixed with the bugfix also? Or do we need to recreate all those ir remotes?
