### ISSUE TITLE
Unable to select a source when using `Input source` in an activity `On sequence`

### ISSUE THREAD

**Issue by uvjim** [unfoldedcircle/feature-and-bug-tracker#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When adding an `Input source` command from the Android TV integration to the `On Sequence` for the activity it doesn't seem possible to set the source that should be switched to.

### How to Reproduce

1. Open the Web Configurator
2. Click Activities & macros
3. Click an activity
4. Find the Input source for an Android TV and drop to the `On sequence`

### Expected behavior

I would expect to be able to specify which source the input should be switched to.

### System version

v1.1.2

### What part of the system affected by the problem?

Web Configurator

**Comment by splattner** [comment]
might be the same issue or related to https://github.com/unfoldedcircle/bug-reports/issues/17 ?

**Comment by zehnm** [comment]
This is most likely the same regression issue as #104, where the selected input source from the dropdown list isn't saved in an activity on- or off-sequence.

**Comment by zehnm** [comment]
Fixed in 1.4.2
Please note that the input source dropdown box is only shown in the activity sequences. It will be added to the UI component and button mapping editor in a future release.
