### ISSUE TITLE
webconfigurator QR code not able to scan with Android

### ISSUE THREAD

**Issue by thomas-amler-idnow** [unfoldedcircle/feature-and-bug-tracker#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The QR code which is being shown in the settings of the remote does not seem to work with my Android devices. Normally my smartphones scan these codes in a fraction of a second. But the codes on my two remotes don't work. With an iPhone 14 it works after 1-2 seconds though.

Phones and software used:
- Xiaomi Poco F2 Pro  with Android 12 and MIUI 14.0.1
  - OEM camera app
  - QR & Barcode scanner from Gamma Play
- Samsung Galaxy S10
  - QR & Barcode scanner from Gamma Play

To find a fix for the problem I stumbled upon this article about the border of QR codes: https://delivr.com/faq/1455/whats-with-the-white-border-around-the-qr-code

To find out if that's the reason why it doesn't work I took a picture with my smartphone from the QR code and edited it with Gimp to have a white border around the QR code. That actually made it work with all hpones instantly. Even the iPhone 14 (which was able to scan the original QR code after a few seconds already) recognized the QR code much faster.

Before editing, not able to scan:
![photo_2023-09-20_16-20-28](https://github.com/unfoldedcircle/bug-reports/assets/63090968/3abc1ead-e6f7-4c0a-8a3b-743f83ac6fde)

After editing, able to scan:
![photo_2023-09-20_16-20-28_qr-fixed](https://github.com/unfoldedcircle/bug-reports/assets/63090968/8fba6068-ac9d-4793-85d9-f350f85cf6e1)

### How to Reproduce

1. Go to remote settings page
2. Tap QR code to increase the size
3. Scan with Smartphone
4. Nothing happening
5. Take a picture from the QR code as flat as possible with your smartphone
6. Load picture into picture editing software, for instance Gimp
7. Add white border around the QR code and make the picture as black/white as possible to increase contrast for the scanner
8. Scan result again with the smartphone
9. and it works

### Expected behavior

Smartphone should receive the URL to the webconfigurator interface.

### System version

v1.2.1

### What part of the system affected by the problem?

UI

**Comment by fbutler** [comment]
I can confirm that I can successfully scan the photo of the non-edited QR code on the remote above with a Samsung S22 running Android 13. It resolves to a RemoteTwo local configurator URL when scanned with the S22. I can't perform the same test with the actual remote yet as I'm awaiting a faulty dock replacement delivery.

**Comment by martonborzak** [comment]
This has been fixed in the latest update.

**Comment by thomas-amler-idnow** [comment]
Thank you very much. It works like a charm now! :heart:
