### ISSUE TITLE
Images are visible twice but are only present once

### ISSUE THREAD

**Issue by mahnkej** [unfoldedcircle/feature-and-bug-tracker#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Images 0, 1, 2 and 3 were uploaded only once but are visible twice. If I delete the named images, the images that are visible twice are also deleted at the same time. When I upload them again, they are visible twice.

<img width="2059" alt="Bildschirmfoto 2023-09-24 um 17 34 56" src="https://github.com/unfoldedcircle/bug-reports/assets/49618399/eb16f5a8-6967-4319-95b1-91f3b189bae2">

### How to Reproduce

Unfortunately, I cannot show any instructions here for better traceability.

### Expected behavior

No double display

### System version

1.2.1

**Comment by zehnm** [comment]
This is caused by #52 because of the invalid icon loading of the icon chooser in the web-configurator.

**Comment by mahnkej** [comment]
Thx for fixing

**Comment by zehnm** [comment]
Fixed in 1.3.3
