### ISSUE TITLE
Updating Dock Firmware: Component Error: 5 Request failed with status code 503

### ISSUE THREAD

**Issue by uvjim** [unfoldedcircle/feature-and-bug-tracker#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When attempting to update the dock firmware from 0.9.0 to 0.9.2 a blank window pops up and an error message appears at the bottom of the screen (see screenshot).

![image](https://github.com/unfoldedcircle/bug-reports/assets/8431065/e60c34f7-13eb-4933-9ca8-78f2fc75af47)

### How to Reproduce

1. Open the Web Configurator
2. Navigate to Integrations & Docks
3. Click on one of the available docks
4. Click Update

### Expected behavior

Expecting the firmware to update

### System version

v1.2.1

**Comment by uvjim** [comment]
This had happened multiple times across multiple browsers. However, after leaving it a while and going to get some lunch, I tried again and it has now worked.

![image](https://github.com/unfoldedcircle/bug-reports/assets/8431065/da165a69-747e-44a0-a532-9a3ebe1b5f42)

**Comment by xBitwinSDKx** [comment]
i have the same issue with both my docks

**Comment by xBitwinSDKx** [comment]
I found something... If I add the dock manually it will not work. 
What I did to make it work:
! Be quick with all the steps you do!
- reset dock
- immediately search for the new dock --> found it then, before I couldn't find it automatically
- Add the new dock
- immediately Update device --> it worked

i just updated my 2 docks like that.... just dont wait too long inbetween the steps

**Comment by zehnm** [comment]
@uvjim do you see anything in the "Core service" logs (Web-configurator settings, Development: Logs) while the update was running?

Unfortunately the web-configurator currently doesn't show more information than the generic error code. Something we definitely have to improve!
If you still encounter this error, please enable the browser developer tools to inspect the returned error payload. Most of the time it contains more useful information.

The 503 error while updating docks means that the "update service is currently not available" and is caused either by low battery of the remote (< 20%), or if there's an issue with the dock communication. 

The 0.9.2 firmware contains a few OTA improvements, so it might be possible that this behaviour is related to the older firmware.

**Comment by uvjim** [comment]
@zehnm the Core service log only goes back to yesterday (even after changing the date range to include the last 4 days) so I can't see back far enough for that.  However, I have a strong suspicion that it may have bee the low battery.

Interestingly the remote does warn of the low battery when trying to update the remote firmware but does not when attempting to update the dock firmware.

**Comment by zehnm** [comment]
Fixed in the just released version 1.6.4
