### ISSUE TITLE
User-defined IR codes - Keys with a slash in the name cannot be deleted

### ISSUE THREAD

**Issue by mahnkej** [unfoldedcircle/feature-and-bug-tracker#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Custom IR Codes - Keys with a slash in their name cannot be deleted. After these have been successfully read in via bulk upload.
<img width="986" alt="Bildschirmfoto 2023-09-26 um 12 44 35" src="https://github.com/unfoldedcircle/bug-reports/assets/49618399/fefc0cd8-bfce-4224-97fa-f86dd9c0799b">

### How to Reproduce

See illustration in the error description

### Expected behavior

It seems that the slash is interpreted as a command. Therefore, when analysing the CSV, pay attention to certain special characters and issue a warning if they are present.

### System version

1.2.1

### What part of the system affected by the problem?

Overall system

**Comment by zehnm** [comment]
Confirmed: URL encoding is missing for IR key name :-(
This then calls an invalid endpoint, e.g. key name `test/1` will call `.../ir/test/1` instead of `.../ir/test%2F1`.
I hope we can get this fixed asap.

**Comment by zehnm** [comment]
Fix will be part of the next update.

**Comment by mahnkej** [comment]
Thx for fixing
