### ISSUE TITLE
Apple TV Integration press-and-hold or long-press interactions all missing

### ISSUE THREAD

**Issue by methnen** [unfoldedcircle/feature-and-bug-tracker#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On Apple TV certain buttons have alternate functionality that you get to by pressing and holding a button on the remote.

For instance pressing and holding forwards or backwards on the direction pad puts the video into fast forward/rewind mode.

Pressing and holding on the play/pause button puts you in edit mode while on the Home Screen.

Pressing and holding the Home button brings up the control center.

Pressing and holding the center/select/confirm button often brings up contextual menus.

These are all quite useful and I've immediately found the fact that they're missing pretty frustrating. The editing of the Home Screen and fast forward/rewind bits and center button ones are particularly useful for my use but I imagine plenty of folks will be missing the ability to hit the Control Center as well.

I'm also noticing that it doesn't look like the remote can detect, a press-and-hold value or at least has no way of setting up that sort of interaction in the current UI.

The Harmony and NEEO remotes I have can handle these interactions though the actual setup of them is much less flexible than on the RemoteTwo.

### How to Reproduce

1. Add Apple TV integration
2. Try to setup any of the press-and-hold type interaction
3. Note that none of the the commands are in the list and there's no way to tell there remote to behave differently when a button has been pressed and held instead of simply clicked

### Expected behavior

To be able to use the press-and-hold interactions with the Apple TV.

### System version

v1.2.1

### What part of the system affected by the problem?

UI, Web Configurator, Integration

### Additional context

See Apple docs on using the Apple TV remote:

https://support.apple.com/en-us/HT205305

**Comment by kennymc-c** [comment]
I took a look at the debug logs of the ATV integration and noticed that this integration is based on pyatv which actually should be able to support input actions like double tap and hold (https://pyatv.dev/documentation/supported_features/#feature-list).
So hopefully this will be integrated soon.

**Comment by Talkabout** [comment]
I don't want to create another feature request for this so mentioning it here: "long-press" assignment should be possible also for "IR Remotes" and "Activity buttons" to assign custom functionality when a button is pressed and hold. This would allow much more flexibility.

**Comment by zehnm** [comment]
Short update: it's in our backlog and the pyatv communication library we are using supports long presses.
After the activity group release I'll have a look. An initial quick improvement could be using free media-player commands like `menu` for long pressing center or home.
The fully configurable long-press functionality (not just for Apple TV) for all R2 buttons & intgrations will take a bit longer.

**Comment by Talkabout** [comment]
Hi @zehnm ,

thanks for the update, much appreciated!

What do you mean with using "media-player commands like menu"? Would that work for AndroidTV also? There I am missing the long press for open the context menu (usually long press of OK button).

**Comment by zehnm** [comment]
@Talkabout until we add custom commands to a media-player entity or support a remote-entity, we are limited to the defined features of the media-player entity (e.g. dpad control, menu, back, home etc). If a feature is not yet used, we can use it for example to send a fixed, long-press command to the Apple TV. The pyatv library defines single-, double-, 1-second-presses for certain commands. So it would be super simple to use the unused media-player menu command for a 1-second command.
I'll test it.

**Comment by kennymc-c** [comment]
@zehnm By "fully configurable long-press functionality" you are also referring to #94 ?

**Comment by Snuffy2** [comment]
@zehnm from your testing, were you able to get something working?

**Comment by kennymc-c** [comment]
Any news? This is one the most important features for me

**Comment by methnen** [comment]
Same, given we use our remote with our Apple TV more than any other device in the house it's pretty much just sitting on the counter getting updates as they roll in until this feature is worked out.

**Comment by martonborzak** [comment]
We're enhancing the media player component with custom command options. This will enable the additon of commands that trigger actions, that are invoked with long presses with traditional remotes.

Short press, repeat and long presses are handled by the UI.

After this enhancement, you'll be able to assign a command to a short press and another command to a long press, basicaly achieving similar functionality as with traditional remotes, where a short and long press invokes a different action.

**Comment by Talkabout** [comment]
Hi @martonborzak,

will that work only for the media_player entity (as mentioned in your comment) or will we be also able to assign short/long press actions directly from UI (so basically 2 separate functions on the same button, one for short and one for long press) for IR commands?

Bye

**Comment by martonborzak** [comment]
@Talkabout see #94

**Comment by zehnm** [comment]
The just released uc-api 0.9.0 supports more media-player features and a "simple command" option for all device commands not covered by a feature: https://github.com/unfoldedcircle/core-api/releases/tag/v0.9.0-beta

Next steps:
- [x] enhance Node.js & Python API wrapper libraries (ETA today)
- [x] enhance firmware (core, UI, web-configurator) (ETA this week) -> released in beta group
- [x] enhance Apple TV integration to support missing commands (open task: refactoring for open source release) -> released in beta group

**Comment by Talkabout** [comment]
Hi @zehnm,

thanks for the update these are very nice features, but they do not really help in terms of physical buttons. As those a very limited it is crucial to have the ability to assign the commands to a long press. Any idea when this will be available?

**Comment by zehnm** [comment]
@Talkabout this is all related and required for supporting more Apple TV functions like long press functionality. Everything goes through the integration API and the functionality is bound by the available entity features.

**Comment by Talkabout** [comment]
@zehnm so it basically means that it will be possible to assign long press commands for media player entities? What about Long press for IR commands? Also included with these changes or following later?

**Comment by zehnm** [comment]
@Talkabout this works for IR remote-entities and activities.

Remote-entity example with IR commands:

<img width="647" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/518fe320-2cbf-4559-97cb-0141abf9ce63">

Activity example with multiple entitites:

<img width="647" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/a382dbb1-9fcb-458e-a996-d58868e8159e">

**Comment by Talkabout** [comment]
That looks VERY nice!!! Thanks @zehnm!

**Comment by zehnm** [comment]
Apple TV integration rewrite is almost done and currently being tested. A beta release is planned for tomorrow with a public release later this week.

New features:
- command support for:
  - context menu
  - control center
  - top menu (back to home screen from within an app)
  - app switching
  - screensaver
- manual setup option with IP address
- common bug fixes
- developers: the integration will be released as open source project by the time of the public release.

Long button press support will be included too in the next firmware release (as generic feature, not just for Apple TV).

**Comment by methnen** [comment]
Awesome. This was one of the last big items preventing me from using this as my primary device. All of it sounds great.

**Comment by zehnm** [comment]
It took a day longer for the beta group release, but multi-device support is now included as well!
For all interested developers: https://github.com/unfoldedcircle/integration-appletv

**Comment by kennymc-c** [comment]
Thanks for the 1.7.4 update! I noticed two thing:
- There is no command for the control center (home button long press)
- The app switcher now has its own command although in previous firmwares you could already open the app switcher with a double press on the home button. This is not possible anymore. Could you bring this functionality back? Double pressing up and down still works inside the app switcher to kill apps so I assume this could be a bug?

**Comment by zehnm** [comment]
> * There is no command for the control center (home button long press)

It's the `settings` command.

> * The app switcher now has its own command although in previous firmwares you could already open the app switcher with a double press on the home button. This is not possible anymore.

That's still possible with the integration and hasn't changed. However, the UI might now prevent fast click actions. 
@martonborzak could you please check this?

**Comment by martonborzak** [comment]
We don't have double press implemented, so if this was doing something like that before that was only accidental.

**Comment by kennymc-c** [comment]
Then I think it would make sense to also implement a double-click of all the individual direction buttons as separate commands maybe called swipe left/right/up/down? Although it currently works without its own command, this seems to be just a coincidence.

**Comment by zehnm** [comment]
> > * There is no command for the control center (home button long press)
> 
> It's the `settings` command.

I just noticed that the `menu` feature is defined but not mapped to a command! So it makes more sense to use this for control center (and removing the `settings` feature). I'll change this in one of the next releases.

@martonborzak what I've meant is if the UI delays somehow the single clicks by the long-press logic? Previously two rapid single clicks triggered the double click action on the ATV. If this is now delayed due to handling long-presses in the UI, it won't work anymore.

> implement a double-click of all the individual direction buttons as separate commands

Makes sense and it's no problem now exposing them as simple commands.

**Comment by martonborzak** [comment]
@zehnm yes, the logic changed for button handling, so previsouly it might have been possible to do rapid presses.

**Comment by zehnm** [comment]
Included in 1.7.4.
Control-center will be mapped to the "Menu" command in 1.7.6
