### ISSUE TITLE
[feature request] Stop activity when starting another one

### ISSUE THREAD

**Issue by Talkabout** [unfoldedcircle/feature-and-bug-tracker#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Situation with 2 activities:

Activity 1
Activity 2

- in "Activity 1" adding "Activity 2" as entity
- in "on sequence" of activity one stopping "Activity 2"

This does not work because I can only choose to start "Activity 2" but not to stop it.

The ultimate goal here is make sure that 2 activities are not running at the same time.

### How to Reproduce

1. create "Activity 1"
2. create "Activity2"
3. add "Activity 2" to entities used in "Activity 1"
4. in "on sequence" of "Activity 1" try to stop "Activity 2"

### Expected behavior

I can choose to stop "Activity 2" in the "on sequence" of "Activity 1"

**Comment by RuudBurger** [comment]
I would like to add a setting on the activity itself to just do "stop all other activities".

**Comment by Talkabout** [comment]
With the activity group concept and the support for the modified off-sequence this topic is closed, thanks!
